from django.urls import path
from . import views
urlpatterns = [
    path('', views.main),
    path('adminhome', views.adminhome),
    path('addbustime', views.AddBusTime),
    path('busmanagement', views.busmanagement),
    path('addconductor', views.addconductor),
    path('busmanagement_add', views.busmanagement_add),
    path('bustimee', views.bustimee,name='bustimee'),
    path('addstop', views.AddStop),
    path('conductor', views.conductor,name="Conductor"),
    path('feedback', views.feedback),
    path('login1', views.main),
    path('passenger', views.passenger),
    path('logout', views.logout, name='logout'),
    path('lt', views.lt, name='lt'),
    path('route', views.Routee),
    path('routeadd', views.RouteAdd),
    path('stopdetails', views.stopdetailz),
    path('map', views.mapview),
    path('track', views.track),
    path('deleteconductor/<int:id>', views.deleteconductor, name="deleteconductor"),
    path('deletestop/<int:id>', views.deletestop, name="deletestop"),
    path('deletebustime/<int:id>', views.deletebustime, name="deletebustime"),
    path('searchticket',views.searchticket),
    path('deleteroute/<int:id>', views.deleteroute, name="deleteroute"),
    path('deletebus/<str:id>', views.deletebus, name="deletebus"),
    path('updatebus/<str:id>', views.updatebus, name="updatebus"),
    path('login', views.userlogin, name="login"),
    path('reg', views.userreg, name="reg"),
    path('selectroute', views.selectroute, name="selectroute"),
    path('viewroutes', views.viewroutes, name="viewroutes"),
    path('bustime', views.androidbustime, name="bustime"),
    path('payment1', views.payment1, name="payment1"),
    path('Bank1', views.Bank1, name="Bank1"),
    path('afeedback', views.afeedback, name="afeedback"),
    path('seastops',views.seastops,name='seastops'),
    path('getalert', views.getalert, name='getalert'),
    path('locationupdate', views.locationupdate, name='locationupdate'),

]
